apiVersion: v1
kind: Service
metadata:
  name: spring-boot-client-service
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080